/*! mmapi v1.3 Copyright 2006-2015 Maxymiser Inc */
/*v1.3.14.63962*/
/*Please do not modify this file except configuration section at the bottom.*/
(function(b,C){function O(a){var b=this,d=a.domain,k=encodeURIComponent,v=decodeURIComponent;b.set=function(a,b,h,f){f||(b=k(b));a=k(a)+"="+b+";domain="+d+";path=/";h?(b=new Date,b.setTime(b.getTime()+864E5*h),h=";expires="+b.toGMTString()):h="";document.cookie=a+h;return this};b.remove=function(a){b.set(a,"",-1);return this};b.get=function(a,b){var d=new RegExp("(?:^|; )"+k(a).replace(/([.$?*|{}()\[\]\\\/+^])/g,"\\$1")+"=([^;]+)"),d=(document.cookie.match(d)||[,""])[1];return b?d:v(d)}}function Q(a){function f(a){for(var b=
{},d="",f=0,e;e=A.getItem(a+f++);)d+=e;"cookie"==w&&(d=decodeURIComponent(d));try{b=JSON.parse(d)}catch(h){}return b}function d(){r=f(G);h=f(D);E&&"cookie"!==w&&(t.set(u+"store.s","s"),E=!1,h={});var a=(new Date).getTime(),b=r[n],d;for(d in b)b.hasOwnProperty(d)&&l(b[d]).e<=a&&delete b[d];v();r[n]=r[n]||{};h[n]=h[n]||{}}function k(b,a,d){a=JSON.stringify(a);var f="{}"===a,e=0;for("cookie"==w&&(a=encodeURIComponent(a));A.getItem(b+e);)A.removeItem(b+e++);if(!f)for(e=0;f=a.substr(3E3*e,3E3);)A.setItem(b+
e++,f,d)}function v(){k(G,r);k(D,h,0)}function l(a){var b=a.indexOf("|");return{v:JSON.parse(a.substring(b+1,a.length)),e:a.substring(0,b)}}if(!/^(cookie)$/.test(a.type))throw"(mm module: storage) Invalid storage type: "+a.type;var r,h,w=a.type||"cookie",u=a.cprefix+".",G=u+"store.p.",D=u+"store.s.",t=new O({domain:a.domain}),n=a.namespace||"def",E=!t.get(u+"store.s"),A="local"===w&&b.localStorage?b.localStorage:"session"===w&&b.sessionStorage?b.sessionStorage:{setItem:function(a,b,d){t.set(a,b,d==
C?365:d,!0)},getItem:function(a){return t.get(a,!0)},removeItem:function(a){t.remove(a)}};this.get=function(a){d();var b=r[n],f=h[n],x={},e;for(e in b)b.hasOwnProperty(e)&&(x[e]=b[e]);for(e in f)f.hasOwnProperty(e)&&(x[e]=f[e]);if(!a){a={};for(var k in x)x.hasOwnProperty(k)&&(a[k]=l(x[k]).v);return a}return(x[a]?l(x[a]):0).v};this.set=function(a,b,f){d();var k=r[n],e=h[n];delete k[a];delete e[a];null!==b&&b!==C&&(f?(e=new Date,e.setTime(e.getTime()+864E5*f),b=e.getTime()+"|"+JSON.stringify(b),k[a]=
b):e[a]="0|"+JSON.stringify(b));v();return this};this.removeAll=function(){d();r[n]={};h[n]={};v();return this};this.testStorage=function(){var a=(""+Math.random()).substring(0,5);t.set(u+"tst",a,10);a=t.get(u+"tst",!0)===a?1:0;t.remove(u+"tst");return a};d()}var l=b.console||{log:function(){},error:function(){}},N=new function(a){function f(c){return"function"===typeof c}function d(c){return"string"===typeof c}function k(c,g){if(z[c])for(var a=z[c].length-1;0<=a;a--)z[c][a].call({},g)}function v(c){if(J){var g=
document.getElementsByTagName("head")[0];g.insertBefore(c,g.lastChild)}else document.write(c.outerHTML||(new XMLSerializer).serializeToString(c))}function F(c,g){var a=document.createElement("script");a.type="text/javascript";a.id=g;a.src=c;return a}function r(c){if("object"!==typeof c)return c;var g=[],a;for(a in c)if(c.hasOwnProperty(a))if(c[a].constructor===Array)for(var b in c[a])c[a].hasOwnProperty(b)&&g.push(a+"="+c[a][b]);else g.push(a+"="+encodeURIComponent(c[a]));return g.join(";")}function h(c){c=
c?E(c):{};var a={};d(c["mm-dlp-api"])&&(a.fv={ref:decodeURIComponent(c["original-ref"]).substring(0,256),url:decodeURIComponent(c["original-url"]).substring(0,1024)},a.origin=/http(s)?:\/\/.*?([^/]|$)+/.exec(a.fv.url)[0]);for(var b in c){var y=c[b];c.hasOwnProperty(b)&&"mmcore."===b.substring(0,7)&&(a[b.substring(7)]=decodeURIComponent(y))}return a}function w(){var c="mmRequestCallbacks["+B+"]",g={},m=b.screen;g.fv={dmn:a.domain,ref:document.referrer.substring(0,256),url:location.href.substring(0,
1024),scrw:m.width,scrh:m.height,clrd:m.colorDepth,cok:p[q.persistent].testStorage()};g.lver="1.3";g.jsncl=c;g.ri=B;return g=e.mergeParams(g,h(location.search))}function u(c,g){var m=c&&c.Packages||[],y=m.length;if(0<y){b.mmInitCallback=function(a){a(e,c,{skipResponseProcessing:!0,skipPersistentData:!0,useLoaderStorage:!0});0===--y&&(g(),b.mmInitCallback=C)};for(var d=0;d<m.length;d++){var f=F(0===m[d].indexOf("//")?m[d]:a.baseContentUrl+m[d],"mmpack."+d);v(f)}}else g()}function G(c){c=document.getElementById(c);
c.parentNode?c.parentNode.removeChild(c):c&&c.removeAttribute("src")}function D(c,a,m){c=(P[c-1]=a)&&a.PersistData||[];for(var y=c.length;y--;)e.setParam(c[y].Name,c[y].Value,q.persistent,c[y].Expiration);if(a.hasOwnProperty("mmcoreResponse")&&d(a.mmcoreResponse)&&b.hasOwnProperty("mmcore"))try{Function(a.mmcoreResponse).call(b)}catch(f){l.log(f)}k("response",a);m(!!a);k("responseExecuted",a)}function t(c,a){var e=F(c,"mmrequest."+B);(function(c,a){b.mmRequestCallbacks[c]=function(g){G(e.id);1===
c?u(g,function(){J=!0;D(c,g,a);var e=h(document.location.search).origin;e&&b.parent&&b.parent.postMessage&&b.parent.postMessage(JSON.stringify({hash:"unhide",command:"unhide",data:{}}),e)}):D(c,g,a);delete b.mmRequestCallbacks[c]}})(B,a);e.setAttribute("onerror","window['mmRequestCallbacks']["+B+"](false);");v(e);B++}function n(){var c={};this.get=function(a){return a?c[a]:c};this.set=function(a,b){c[a]=b};this.removeAll=function(){c={}}}function E(c){c=c.split(/\?|&/);for(var a={},b,e=0;e<c.length;e++)c[e]&&
(b=c[e].split("="),a[b[0]]=b[1]||"");return a}function A(c){var a={},b=E(c);K||(a.pageid=b.pageid);a.jsver=b.jsver;if(c=b.uv){a.uv={};c=decodeURIComponent(c);var e=c.split(/;/);for(c=0;c<e.length;c++){var d=e[c].split("="),f=d[0].replace(/^\s+|\s+$/gm,""),d=d[1];0<f.length&&(a.uv.hasOwnProperty(f)||(a.uv[f]=[]),a.uv[f].push(d))}}if(c=b.uat)for(a.uat={},c=decodeURIComponent(c),b=c.split(/;/),c=0;c<b.length;c++)e=b[c].split("="),f=e[0].replace(/^\s+|\s+$/gm,""),d=e[1],0<f.length&&(a.uat[f]=d);return a}
function N(){if(b.hasOwnProperty("mmcore")){var c=b.mmcore;c.server=a.srv;e.CGRequestInternal=e.CGRequest;e.CGRequest=function(a,b){K=!0;L=a;M=b;c.CGRequest()};var g=c._Tag;c._Tag=function(b){if(-1==b.indexOf(a.srv))g.apply(c,arguments);else{c._Clear.call(c);var d=e.mergeParams(M,A(b));e.CGRequestInternal(L,d);M=L=C;K=!1}};var d=c.SetCookie;c.SetCookie=function(a){/^(mmid|pd|srv)$/.test(a)||d.apply(c,arguments)}}}function H(c){return c||b.location.hostname.replace(/^www\./i,"")}function I(c,a,b){var f=
"";0<a.length&&"."!=a.substring(a.length-1)&&(f=".");a=a+f+b;f=c.get(a);d(f)&&f&&(e.setParam(b,f,q.persistent,365),c.remove(a))}function x(a){var e;e=b.hasOwnProperty("mmcore")&&b.mmcore.cookie_domain?b.mmcore.cookie_domain:a.hasOwnProperty("mmcoreCookieDomain")&&d(a.mmcoreCookieDomain)?a.mmcoreCookieDomain:a.cookie_domain;a=b.hasOwnProperty("mmcore")&&b.mmcore.cprefix?b.mmcore.cprefix:a.hasOwnProperty("mmcoreCprefix")&&d(a.mmcoreCprefix)?a.mmcoreCprefix:a.cprefix+".";e=new O({domain:H(e)});I(e,a,
"pd");I(e,a,"srv");I(e,"","mmid")}this.version="1.3";var e=this,P=[],B=1,J=!1,z={},p=[],q={persistent:0,deferredRequest:1,request:2,page:3};this.baseStorage=function(c){return new Q({type:a.storageType,namespace:c,domain:H(a.cookie_domain),cprefix:a.cprefix})};this.baseStorage.storeStrategy=q;this.mergeParams=function(a,b){a="undefined"===typeof a?{}:a;b="undefined"===typeof b?{}:b;if("object"!==typeof b)return b;var d={},f;if("object"===typeof a)for(f in a)a.hasOwnProperty(f)&&(d[f]=a[f]);for(f in b)b.hasOwnProperty(f)&&
(d[f]=d[f]?d[f].constructor===Array&&b[f].constructor===Array?d[f].concat(b[f]):e.mergeParams(d[f],b[f]):b[f]);return d};this.CGRequest=function(c,d){c=c||function(){};d=d||{};b.mmRequestCallbacks=b.mmRequestCallbacks||{};k("request");var f=e.mergeParams(w(),e.mergeParams(p[q.persistent].get(),e.mergeParams(p[q.deferredRequest].get(),e.mergeParams(p[q.page].get(),p[q.request].get())))),h=[],n=a.srv,f=e.mergeParams(f,d),l;for(l in f)f.hasOwnProperty(l)&&h.push(encodeURIComponent(l)+"="+encodeURIComponent(r(f[l])));
p[q.deferredRequest].removeAll();p[q.request].removeAll();t(n+h.join("&"),c);return this};this.getResponses=function(){return P};this.setParam=function(a,b,e,d){p[e].set(a,b,d);return this};this.getParam=function(a,b){return p[b].get(a)};this.removeParam=function(a,b){p[b].set(a,null,-1);return this};this.on=function(a,b){z[a]&&z[a].push(b);return e};var L,M,K=!1;(function(a){function g(){e.on("request",function(){try{var b=a.beforeRequest;f(b)&&b.call({},e.getParam,function(a,b,c,d){e.setParam(a,
b,"undefined"===typeof c?1:c,d)})}catch(d){l&&l.log(d)}});e.on("response",function(b){try{var d=a.afterResponse;f(d)&&d.call({},e.getParam,function(a,b,c,d){e.setParam(a,b,"undefined"===typeof c?1:c,d)},b)}catch(g){l&&l.log(g)}});e.on("responseExecuted",function(b){try{var d=a.afterResponseExecution;f(d)&&d.call({},e.getParam,function(a,b,c,d){e.setParam(a,b,"undefined"===typeof c?1:c,d)},b)}catch(g){l&&l.log(g)}});try{var g=a.beforeInit;g&&"function"===typeof g&&g.call({},e.getParam,function(a,b,
c,d){e.setParam(a,b,"undefined"===typeof c?1:c,d)})}catch(h){l&&l.log(h)}a.hasOwnProperty("mmcoreUrl")&&d(a.mmcoreUrl)&&a.mmcoreUrl?(b.mmcoreInitCallback=function(d){x(a);N();e.CGRequest(function(){f(d)&&d.apply(b.mmcore,arguments)},k);delete b.mmcoreInitCallback},v(F(a.mmcoreUrl,"mmcoreIntegration"))):(x(a),e.CGRequest(C,k))}for(var m in a)a.hasOwnProperty(m)&&(e[m]=a[m]);e.calcCookieDomain=H(e.cookie_domain);J="boolean"===typeof a.async?a.async:!1;p[q.persistent]=e.baseStorage("mmparams.p");p[q.deferredRequest]=
e.baseStorage("mmparams.d");p[q.request]=new n;p[q.page]=new n;z.request=[];z.response=[];z.responseExecuted=[];var k={};m=h(document.referrer).pruh;var r=h(document.location.search).pruh,t=b.mmpruh,u=e.getParam("pruh",0),w=(m?m+",":"")+(r?r+",":"")+(t?t+",":"")+(u?u:"");w?(b.mmInitCallback=function(a){a(e,w,g)},v(F(a.baseContentUrl+"utils/pruh.js","MM.PRUH"))):g()})(a);return this}({
 storageType:'cookie',
 cprefix:'mmapi',
 domain:'aerlingus.com',
 baseContentUrl:'//service.maxymiser.net/platform/eu/api/',
 cookie_domain:location.hostname.match(/^[\d.]+$|/)[0]||('.'+(location.hostname.match(/[^.]+\.((eu|us|uk|cn)\.com|\w{2,3}\.\w{2}|\w{2,})$/)||[location.hostname])[0]),
 srv:'//service.maxymiser.net/cg/v5/?',
 async:false,
 mmcoreUrl:'',
 mmcoreCookieDomain:'',
 mmcoreCprefix:'',
 beforeInit:function( getParam, setParam ){   },
 beforeRequest:function( getParam, setParam ){   },
 afterResponse:function( getParam, setParam, genInfo ){   },
 afterResponseExecution:function( getParam, setParam, genInfo ){   }
});b.mmsystem=new function(a){this.enableUtility=function(b){var d=a.getParam("un",a.baseStorage.storeStrategy.persistent)||"";(new RegExp("(^|,)"+b+"($|,)")).test(d)||(d=d.split(","),d.push(b),a.setParam("un",d.join(",").replace(/(^,)|(,$)/g,""),a.baseStorage.storeStrategy.persistent));return this};this.disableUtility=function(b){var d=a.getParam("un",
a.baseStorage.storeStrategy.persistent)||"";(new RegExp("(^|,)"+b+"($|,)")).test(d)&&(d=d.replace(new RegExp("(^|,)"+b+"($|,)","gi"),",").replace(/(^,)|(,$)/g,""),a.setParam("un",d,a.baseStorage.storeStrategy.persistent));return this};this.getConfig=function(){return{storageType:a.storageType,cprefix:a.cprefix,domain:a.domain,baseContentUrl:a.baseContentUrl,cookie_domain:a.cookie_domain,srv:a.srv,async:a.async,beforeInit:a.beforeInit,beforeRequest:a.beforeRequest,afterResponse:a.afterResponse,afterResponseExecution:a.afterResponseExecution}}}(N)})(window);